#!/usr/bin/env bash
set -e

find_local_gemsets_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.ruby-gemsets" ]; then
      echo "${root}/.ruby-gemsets"
      exit
    elif [ -e "${root}/.rbenv-gemsets" ]; then
      echo "${root}/.rbenv-gemsets"
      exit
    fi
    root="${root%/*}"
  done
}

if [ -z "$RBENV_GEMSET_FILE" ]; then
  find_local_gemsets_file "$RBENV_DIR"
  [ "$RBENV_DIR" = "$PWD" ] || find_local_gemsets_file "$PWD"
elif [ -e "$RBENV_GEMSET_FILE" ]; then
  echo "$RBENV_GEMSET_FILE"
  exit
fi

exit 1
