#!/usr/bin/env bash
set -e

gemset_file="$(rbenv-gemset-file 2>/dev/null || true)"

if [ -n "$RBENV_GEMSETS" ]; then
  echo $RBENV_GEMSETS
elif [ -n "$gemset_file" ]; then
  RBENV_GEMSETS=$(cat "$gemset_file" | grep -v '^[+|-]')
  GEMSET_OPTIONS="$(rbenv-gemset options 2>/dev/null)"
  if [[ ! $GEMSET_OPTIONS =~ '-global' ]]; then
    if echo $RBENV_GEMSETS | grep -v '\bglobal\b' >/dev/null 2>&1; then
      RBENV_GEMSETS="$RBENV_GEMSETS global"
    fi
  fi
  echo $RBENV_GEMSETS
else
  echo "no active gemsets" >&2
  exit 1
fi


