#!/usr/bin/env bash
set -e

for version in $(rbenv versions --bare); do
  shopt -s nullglob
  gemsets=($(rbenv prefix "$version")/gemsets/*)
  shopt -u nullglob

  if [ -n "$gemsets" ]; then
    echo "$version:"
    for gemset in ${gemsets[@]}; do
      echo "  ${gemset##*/}"
    done
  fi
done
