#!/usr/bin/env bash
set -e

if [[ -f .rbenv-gemsets ]]; then
  echo ".rbenv-gemsets already present" >&2
  exit 1
fi

RBENV_GEMSET="$1"

if [ -z "$RBENV_GEMSET" ]; then
  RBENV_GEMSET=$(basename "$PWD")
  if [[ "$RBENV_GEMSET" =~ [[:space:]] ]]; then
    echo "current folder name contains spaces - can't inherit gemset name from it; please, provide your own" >&2
    exit 1
  fi
fi

rbenv gemset create "$(rbenv version-name)" $RBENV_GEMSET
echo $RBENV_GEMSET > .rbenv-gemsets

echo created and initialized the following gemset for use with $(rbenv version-name)
echo =====
echo $RBENV_GEMSET
echo =====
