#!/usr/bin/env bash
set -e

gemset_file="$(rbenv-gemset-file 2>/dev/null || true)"

if [ -n "$RBENV_GEMSETS" ]; then
  echo $RBENV_GEMSETS
elif [ -n "$gemset_file" ]; then
  RBENV_GEMSETS=$(cat "$gemset_file")
  if [ "$(rbenv-gemset-option disable-global-gemset)" != "yes" ]; then
    has_global='\bglobal\b'
    if [[ ! $RBENV_GEMSETS =~ $has_global ]]; then
      RBENV_GEMSETS="$RBENV_GEMSETS global"
    fi
  fi
  echo $RBENV_GEMSETS
else
  echo "no active gemsets" >&2
  exit 1
fi


