#!/usr/bin/env bash
set -e

for version in "$RBENV_ROOT"/versions/*; do
  shopt -s nullglob
  gemsets=("$version"/gemsets/*)
  shopt -u nullglob

  if [ -n "$gemsets" ]; then
    echo ${version##*/}:
    for gemset in "${gemsets[@]}"; do
      echo "  ${gemset##*/}"
    done
  fi
done
